apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: daily7days
  namespace: yelb
spec:
  disabled: false  # optional
  retention:
    expires: "168h"  # optional
    maxCount: 7  # optional
  schedule: "0 18 * * *"
  snapshotTemplate:
    # labels:  # optional
    #   mylabel: snap
    snapshotClassName: csi-rbdplugin-snapclass  # optional
