apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: default
  resourceVersion: "7336660"
  selfLink: /apis/apps/v1/namespaces/default/deployments/coffee
  uid: 157c5ba8-360b-45a3-adf5-29fa7484adc8
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coffee
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coffee
    spec:
      containers:
      - image: nginxdemos/nginx-hello:plain-text
        imagePullPolicy: IfNotPresent
        name: coffee
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: "4Gi"
          requests:
            cpu: 200m
            ephemeral-storage: "2Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-01-16T05:43:50Z"
    lastUpdateTime: "2021-01-16T05:43:52Z"
    message: ReplicaSet "coffee-6c8998cf9c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-01-27T00:12:12Z"
    lastUpdateTime: "2021-01-27T00:12:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
