apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: felice-vpa
  namespace:  kafka
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       felice-spark-felice

# POD 내 전체 컨테이너에 (6개 pod 등) 적용되는 spec 
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 1Gi
        maxAllowed:
          cpu: 2
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Auto"
