apiVersion: v1
data:
  postgresql.conf: |
    max_locks_per_transaction = '512'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: postgresql
    meta.helm.sh/release-namespace: postgresql
  labels:
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.4.8
  name: postgresql-configuration
  namespace: postgresql
