apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-pvc-deploy
  labels:
    app: date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date
  template:    
    metadata:
      labels:
        app: date
    spec:
      containers:
      - name: date-pod
        image: centos:7.5.1804
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /nfs/pod-out.txt; sleep 10; done"
        volumeMounts:
        - name: nfs-vol
          mountPath: /nfs
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs01-pvc  ## PVC 이름 지정
