apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs01-pvc
  # namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "rook-cephfs"  # PV를 사용하는 경우 SC 이름 지정하지 않음
  # storageClassName: ""  # PV를 사용하는 경우 SC 이름 지정하지 않음
  # volumeName: nfs01-pv  # PV 이름 지정
  resources:
    requests:
      storage: 10Gi  # Max to 적정 용량으로 변경
