kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-cm
data:
  fio-read.job: |
    [global]
    ioengine=libaio
    rw=randrw
    numjobs=16
    direct=1
    bs=4k
    runtime=120
    time_based=1
    iodepth=16
    size=1g
    group_reporting
    rwmixread=100
    rwmixwrite=0
    directory=/scratch/
    [read]
    # ioengine=psync
    # direct=1
    # buffered=0
    # size=10G
    # iodepth=1000
    # numjobs=100
    # group_reporting
    # refill_buffers
    # rwmixread=80
    # norandommap
    # randrepeat=0
    # percentage_random=0
    # bs=512K
    # buffer_compress_percentage=50
    # rw=read
    # [testjob]

  fio-write.job: |
    [global]
    ioengine=libaio
    rw=randrw
    numjobs=16
    direct=1
    bs=4k
    runtime=120
    time_based=1
    iodepth=16
    size=1g
    group_reporting
    rwmixread=0
    rwmixwrite=100
    directory=/scratch/
    [write]
