apiVersion: apps/v1
kind: Deployment
metadata:
  name: cent-vdi
  namespace: kvdi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cent-vdi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cent-vdi
      annotations:
        diamanti.com/endpoint0: '{"network":"blue", "perfTier":"high"}'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cent-vdi
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: gui
        image: nkkim/centos7-xfce
        imagePullPolicy: Always
        env:
        - name: USER
          value: test
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-password
              key: password
        - name: ROOT
          value: "no"
        resources:
          limits:
            cpu: 150m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - ALL
        #   privileged: false
        #   readOnlyRootFilesystem: true
          # runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
