apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:  # 선택해야 할 POD 선택
    app: nginx  # POD Label 과 동일
