apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: default
spec:
  accessModes:
  # - ReadWriteOnce  ## block accessmode 지정 
  - ReadWriteMany  ## block accessmode 지정 
  resources:
    requests:
      storage: 1Gi
      # storage: 1Ti  # 노드 Disk 용량을 넘으면 할당이 안 됨
  # storageClassName: "openebs-hostpath"  ## SC 지정, default 자동 할당 안됨
  storageClassName: "high" 
  # storageClassName: "rook-ceph-block"  
  # storageClassName: "ebs-sc" 
  # storageClassName: "high"  
  # storageClassName: "rook-nfs-share1" 
  