apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: high2m-pvc
  namespace: default 
spec:
  accessModes:
  - ReadWriteOnce  ## block accessmode 지정 
  resources:
    requests:
      storage: 10Gi
  storageClassName: "high2m"  ## SC 지정