apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd  # 반드시 argocd namespace여야 한다
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 02.nginx
    repoURL: https://172.16.121.146/jerry/bizcubex.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true