apiVersion: v1
kind: Service
metadata:
  labels:
    name: cadvisor-svc
  name: cadvisor-svc
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: cadvisor
    port: 8080
    targetPort: 8080
  #   protocol: TCP
  #   targetPort: 5201
  # sessionAffinity: None
  selector:  # 선택해야 할 POD 선택
    name: cadvisor  # POD Label 과 동일
