apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: httpd
  type: NodePort