apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx  #service가 바라보는 label이 아님. 주의.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx  # Service가 바라보는 label 지정 
    spec:
      containers:
      - name: nginx
        # image: nginxdemos/hello
        image: nginx