apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 80
  #   protocol: TCP
  #   targetPort: 5201
  # sessionAffinity: None
  selector:  # 선택해야 할 POD 선택
    app: nginx  # Deploy Label 과 동일
