apiVersion: v1
kind: Service
metadata:
  name: fedora-svc
  # namespace: nginx
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    nodePort: 30022
  selector:
    kubevirt.io: virt-launcher
    # kubevirt.io/created-by: 5a4c1675-3554-4b26-8f11-4c04f93db633
  type: NodePort
