apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client
  namespace: default
  labels:
    app: nfs-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client  # POD label과 일치
  template:    
    metadata:
      labels:
        app: nfs-client # Selector label과 일치
    spec:
      containers:
      - name: nfs-client
        image: d3fk/nfs-client
        command:
        - "/bin/sh"
        - "-c"
        - "sleep inf"
