apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # PV를 사용하는 경우 SC 이름 지정하지 않음
  volumeName: nfs-pv  # PV 이름 지정
  resources:
    requests:
      storage: 100Gi  # Max to 적정 용량으로 변경
