apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nfs-biz-pvc
#  namespace: bizcube-test  # 사용할 POD의 ns 지정 
spec:
 volumeName: nfs-biz-pv
 storageClassName: ""
 accessModes:
 - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
