apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx
    meta.helm.sh/release-namespace: nginx
    prometheus.io/port: "9113"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-11-02T22:55:56Z"
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-7.1.5
  name: nginx
  namespace: nginx
  resourceVersion: "115909"
  selfLink: /api/v1/namespaces/nginx/services/nginx
  uid: 66bb34ad-fa77-4071-947e-f1a8356c0383
spec:
  clusterIP: 10.0.0.199
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
