apiVersion: v1
kind: Service
metadata:
  name: webrtc-nodeport-svc
  # namespace: dmz-webrtc-cloud
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30020
  selector:
    app: webrtc
  type: NodePort