apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: webrtc
  name: webrtc
  # namespace: dmz-webrtc-cloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webrtc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webrtc
      annotations:    # You must add these two lines under spec-> template -> metadata
        diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
    spec:
      containers:
      - image: spreed/webrtc
        imagePullPolicy: Always
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        #   successThreshold: 1
        #   timeoutSeconds: 1
        name: webrtc
        ports:
        - containerPort: 8443
          protocol: TCP
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        #   successThreshold: 1
        #   timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /srv/extra
          name: data  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
      - name: data
        persistentVolumeClaim:
          # claimName: high-pvc   ## PVC 이름 지정
          claimName: webrtc-pvc   