# resource limit, podAntiAffinity, local time sync
# readiness/linveness probe 
# network annotations 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-tmp
  # namespace 별도 지정 권고
  namespace: default
  labels:
    app: iperf
spec:
  replicas: 2  # 향후 이중화 필요 
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      labels:
        app: iperf
      annotations:
        diamanti.com/endpoint0: '{"network":"blue", "perfTier":"high"}'
    spec:
    # node 중복 방지를 위한 affinity 추가
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iperf
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: iperf
        image: networkstatic/iperf3
        # imagePullPolicy: Always  # 향후 운영 시 IfNotPresent 변경
        command:
        - /bin/sh
        - -c
        - sleep inf
        ports:
        - containerPort: 5201
        # resource 추가 
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        # local host node 시간 동기화
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        # readiness, liveness probe 추가 권고 
      # imagePullSecrets:
      # - name: nexus-secret
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
