apiVersion: dataservice.diamanti.com/v1alpha1
kind: Replication
metadata:
  name: source-rep1
  namespace: default
  annotations:
    replicationDriver: diamanti/replication-driver:v0.1.22
    imagePullPolicy: IfNotPresent
    # Add the follwing annotation in case of openshift cluster
    # k8s.v1.cni.cncf.io/networks: ADDITIONAL_NETWORK_NAME
spec:
  # Add fields here
    role: source
    pvcGroupName: source-pvcgroup
    pvcGroupNameSpace: default
    snapshotPromotor: diamanti 
    failoverPolicy: Automatic
    failbackPolicy: Manual
    rlinks:
      - rlinkName: source
        remoteClusterId: XYZ
        schedule: "*/2 * * * *"
        mode: periodic
        bandwidth: 2 Gbps
        transportType: tcp/ip
        datagramType: block
        compressionOn: yes
        encryptionOn: no
        overflowplicy: skipToNext
        localEndpoint: source-endpoint:9001
        remoteIpAddress: 10.10.190.33:9002
        pvcMap:
           source-pvc1: 'default-pvc'
