apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    diamanti.com/endpoint: none
spec:
  restartPolicy: Never
  containers:
  - name: test-pod
    image: centos:7.5.1804
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 30; done"
    volumeMounts:
    - name: test-pvc
      mountPath: /data
  volumes:
  - name: test-pvc
    persistentVolumeClaim:
      claimName: test-pvc
