---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-server-pvc
  namespace: nfs
spec:
  storageClassName: high2m
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs
  labels:
    app: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
      annotations:
        diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-export
      volumes:
        - name: nfs-export
          persistentVolumeClaim:
            claimName: nfs-server-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: nfs
  labels:
    app: nfs-server
spec:
  type : ClusterIP
  clusterIP: None
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server
