global:
  resolve_timeout: 5m
route:
  receiver: 'email-alert'
  group_by: ['job', 'node', 'namespace', 'pod_name']
 
 
  routes:
  - receiver: 'email-alert'
    # When a new group of alerts is created by an incoming alert, wait at
    # least 'group_wait' to send the initial notification.
    # This way ensures that you get multiple alerts for the same group that 
    #start firing shortly after another are batched together on the first 
    # notification.
    group_wait: 50s
    # When the first notification was sent, wait 'group_interval' to send a 
    # batch of new alerts that started firing for that group.  
    group_interval: 5m
    # If an alert has successfully been sent, wait 'repeat_interval' to
    # resend them.
    repeat_interval: 12h
 
receivers:
- name: email-alert
  email_configs:
  - to: leejunghoon@spkr.co.kr, nkkim@spkr.co.kr
    from: erdia22@gmail.com
    # Your smtp server address
    smarthost: smtp.gmail.com:587
    auth_username: erdia22@gmail.com
    auth_identity: erdia22@gmail.com
    auth_password: oilyrxxoubvifeqe