apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30030
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort