{
 "title": "K10 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster" }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "Backup Exports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Exports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_count{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Policy Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_ended_count{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Policy Runs Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_skipped_count{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Catalog Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalog_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Catalog Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-catalog_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-jobs_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logging_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-logging_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}