kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-cstor-vol
  namespace: default
spec:
  storageClassName: cstor-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
