apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-minio
spec:
  commonName: minio.example.com
  secretName: tls-minio
  dnsNames:
    # Ingress domain
    - minio.example.com
    # Internal domain
    - minio-hl-svc
    - minio-hl-svc.default.svc.cluster.local
  issuerRef:
    name: selfsigning-issuer
