apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2020-10-27T18:36:30Z"
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-0.21.2
  name: my-kafka-headless
  namespace: kafka
  resourceVersion: "8902318"
  selfLink: /api/v1/namespaces/kafka/services/my-kafka-headless
  uid: bf5dd83a-84a0-4ac1-afd8-f8620443f75a
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
