---
apiVersion: v1
kind: Service
metadata:
  name: trivy-server
  namespace: trivy-server
  labels:
    app: trivy-server
spec:
  type: ClusterIP
  selector:
    app: trivy-server
  ports:
    - protocol: TCP
      port: 4954
      targetPort: 4954
