apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win10-data
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 80Gi
  storageClassName: high
