apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: CollectD
    name: cadvisor-svc
  name: cadvisor-svc
  namespace: diamanti-system
spec:
  ports:
  - name: cadvisor
    port: 4194
  selector:
    diamanti.com/app: collectd
