apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
    prometheus.io/scrape: "true"
  labels:
    app: prometheus-node-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-node-exporter-1.16.2
    heritage: Helm
    jobLabel: node-exporter
    release: prometheus
  name: node-exporter-nodeport
  namespace: prometheus
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9100
  selector:
    app: prometheus-node-exporter
    release: prometheus
