kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-hostpath-pvc
  namespace: default
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G