apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: nginx
spec:
  accessModes:
  - ReadWriteOnce  ## block accessmode 지정 
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"  ## SC 이름 지정
