apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatproject1-deployment
  namespace: bizcube-test
  labels:
    app: tomcatproject1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatproject1
  template:
    metadata:
      labels:
        app: tomcatproject1
    spec:
      containers:
      - name: tomcatproject1
        image: tomcat:8.5.57-jdk8-openjdk
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 8080
