# fio 실행 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
spec:
  serviceName: fio
  replicas: 1
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: 
        - "/bin/sh"
        - -c
        - sleep inf
        # ["fio"]
        # args: ["/configs/fio.job", "--output=randwirte.out"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-cm
  volumeClaimTemplates:
  - metadata:
      name: fio-data
    spec:
      storageClassName: high
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
