apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: maria-backup-erp
  namespace: mariadb
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: BPATH
              value: /home/mysql/backup
            - name: HOST
              value: localhost
            - name: PORT
              value: "13306"
            - name: NAMESPACE
              value: mariadb
            - name: STSNAME
              value: mariadb-erp
            - name: CLUSTER
              value: 10.60.0.40:443
            - name: DELETE_LOG
              value: "3"
            - name: SA
              value: spk-admin-user
            - name: CA_DATA
              valueFrom:
                secretKeyRef:
                  key: ca_data
                  name: secret-mariabackup
            - name: TOKEN_DATA
              valueFrom:
                secretKeyRef:
                  key: token_data
                  name: secret-mariabackup
            image: gitlab.dz-army.io:5050/jerry/dz-army/mariadb-backup:1.0
            imagePullPolicy: Always
            name: mariadb
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/localtime
              name: mariadb-localtime
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 0
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /etc/localtime
              type: File
            name: mariadb-localtime
  schedule: 0 1 * * *
  successfulJobsHistoryLimit: 1
  suspend: false
status: {}
