apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: default
spec:
  serviceName: "nginx"
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
# endpointPrefix 지정, 순서대로 할당됨 
        diamanti.com/endpoint0: '{"endpointPrefix":"ac1-web-db","perfTier":"high"}' 
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "high"
      resources:
        requests:
          storage: 1Gi  # SC 지정 없으면 default SC(best-effort) 사용  
