apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snapscheduler.fullname" . }}
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snapscheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snapscheduler.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "snapscheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/manager"]
          args: ["--enable-leader-election"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tagOverride }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  {{- /*
  The horrible-ness below related to nodeSelector is because the node labels
  removed the beta prefix in 1.14.
  We want to have a default that ensures amd64/linux by default, but users must
  be able to override that, including removing all selectors. If we didn't have
  to determine at render-time the proper label name, the default labels should
  be in the values.yaml and the template would look just like affinity, below.
  The values.yaml file would set the labels like it does for resources.
  When support for 1.13 is dropped, please fix this!
  */ -}}
  {{- if quote .Values.nodeSelector | ne "" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- else }}
      nodeSelector:
      {{- if semverCompare ">=1.14" .Capabilities.KubeVersion.Version }}
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      {{- else }}
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
      {{- end }}
  {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapscheduler.fullname" . }}-metrics
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    {{- include "snapscheduler.selectorLabels" . | nindent 4 }}
