# 평문으로 password 입력 가능

apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: tektontest
  annotations:
    tekton.dev/docker-0: docker.xxx.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
