apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  # POD label과 일치
  template:    
    metadata:
      labels:
        app: nginx # Selector label과 일치
    spec:
      containers:
      - name: nginx
        image: harbor.spk.io/test/nginx:1.0