---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: collectd-svc
  name: collectd-svc
  namespace: diamanti-system
spec:
  ports:
  - name: cadvisor
    port: 4194
    protocol: TCP
    targetPort: 4194
  selector:
    diamanti.com/app: collectd
  type: ClusterIP
---

