{{- if semverCompare ">=1.17-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: imxc-restricted-rb
  namespace: imxc
subjects:
  - kind: ServiceAccount
    name: default
    namespace: imxc
roleRef:
  kind: ClusterRole
  name: imxc-cluster-role
  apiGroup: rbac.authorization.k8s.io
