apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  # name: redis-snapshot-100g
  name: grafana-snapshot
spec:
  volumeSnapshotClassName: ebs-csi-aws  # snapshot class 지정
  # volumeSnapshotClassName: default-snapclass  # snapshot class 지정
  source:
    persistentVolumeClaimName: grafana  # 백업 대상 PVC 지정