apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snap02-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: snap02
