apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo  
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 256Mi
    args:
    - -cpus
    - "2"
  nodeSelector:
    nodetype: asterisk-in

        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 10Gi
        #   requests:
        #     cpu: "0.5"
        #     memory: 1Gi
