apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-redis-pvc
    namespace: yelb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 200Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: redis-pvc