apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: test
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'  # network 이름 지정
    spec:
      containers:
      - name: nginx
        # image: k8s.gcr.io/nginx-slim:0.8
        image: nginx
        ports:
        - containerPort: 80
          name: web
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 80
        #   failureThreshold: 15
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 1
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "high"
      resources:
        requests:
          storage: 1Gi  # SC 지정 없으면 default SC(best-effort) 사용  
