apiVersion: v2
appVersion: 0.8.0
description: A subproject of Apache NiFi to store and manage shared resources.
home: https://github.com/dysnix/charts/tree/master/nifi-registry
maintainers:
- email: daniel@dysnix.com
  name: daniel-yavorovich
name: nifi-registry
type: application
version: 0.3.2
