apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: date-pvc
#  namespace: diamanti-system
spec:
  accessModes:
  - ReadWriteOnce  ## block accessmode 지정 
  resources:
    requests:
      storage: 10Gi
  storageClassName: "high"  ## SC 지정
