apiVersion: v1
kind: List
items:
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
- apiVersion: apps/v1
{{- else }}
- apiVersion: extensions/v1beta1
{{- end }}
  kind: Deployment
  metadata:
    name: jaeger-agent
    namespace: imxc
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
  spec:
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
    selector:
      matchLabels:
        app: jaeger
  {{- end }}
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger
          app.kubernetes.io/name: jaeger
          app.kubernetes.io/component: agent
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "5778"
          diamanti.com/endpoint0: '{"network":"imxc","perfTier":"best-effort"}'
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        containers:
        - image: {{ .Values.global.HARBOR_URL }}/{{ .Values.global.HARBOR_PROJECT }}/jaegertracing/jaeger-agent:{{ .Values.global.IMXC_RELEASE_VERSION }}
          name: jaeger-agent
          args: ["--reporter.grpc.host-port", "jaeger-collector:14250"]
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
          - containerPort: 5778
            protocol: TCP
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: LOG_MAXAGE
            value: "1"
          - name: LOG_MAXBACKUPS
            value: "3"
          - name: LOG_MAXSIZE
            value: "100"
          - name: LOG_STDOUT
            value: "TRUE"
          - name: LOG_FILENAME
            value: "jaeger-agent"

- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: imxc
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
  spec:
    clusterIP: {{ .Values.global.JAEGER_AGENT_CLUSTER_IP }}
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: 5778
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
    type: ClusterIP

