apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kxdb
  name: kxdb
  # namespace: polaris
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kxdb
      annotations:
        diamanti.com/endpoint0: '{"network":"blue", "perfTier":"high"}'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kxdb
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: harbor.spk.io:5050/jerry/admin/kdb:0.14
        # imagePullPolicy: Always
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        #   successThreshold: 1
        #   timeoutSeconds: 1
        name: kxdb
        command:
        - "/bin/sh"
        - "-c"
        - "sleep inf"
        ports:
        - containerPort: 3010
          protocol: TCP
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        #   successThreshold: 1
        #   timeoutSeconds: 1
        resources:
          limits:
            cpu: 8000m
            memory: 64Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /data
          name: db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
      - name: db-data
        persistentVolumeClaim:
          # claimName: high-pvc   ## PVC 이름 지정
          claimName: kxdb-pvc   
