apiVersion: v1
data:
  default-fio: |
    [global]
    randrepeat=0
    verify=0
    ioengine=libaio
    direct=1
    gtod_reduce=1
    [job1]
    name=read_iops
    bs=4K
    iodepth=64
    size=2G
    readwrite=randread
    time_based
    ramp_time=2s
    runtime=15s
    [job2]
    name=write_iops
    bs=4K
    iodepth=64
    size=2G
    readwrite=randwrite
    time_based
    ramp_time=2s
    runtime=15s
    [job3]
    name=read_bw
    bs=128K
    iodepth=64
    size=2G
    readwrite=randread
    time_based
    ramp_time=2s
    runtime=15s
    [job4]
    name=write_bw
    bs=128k
    iodepth=64
    size=2G
    readwrite=randwrite
    time_based
    ramp_time=2s
    runtime=15s
kind: ConfigMap
metadata:
  labels:
    createdbyfio: "true"
  name: kubestr-fiowfjcr
  namespace: default
kind: List
metadata:
resourceVersion: ""
selfLink: ""
