apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  # namespace: default
spec:
  containers:
  - name: busybox
    # image: busybox
    image: busybox:1.28.0
    # args:  # entrypoint 
    # - sleep
    # - "1000000"
    resources:
      limits:
        cpu: 150m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 1000"

    # volumeMounts:  
    # - name: date-vol  # Volume 이름
    #   mountPath: /data  # Mount 이름 
  volumes:  # 어떤 Volume을 사용할 것인지
  - name: date-vol
    persistentVolumeClaim:
      claimName: default01-pvc   
