apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   diamanti.com/endpoint0: '{"network":"web","perfTier":"high"}'  # network 이름 지정
  name: nginx
spec:
  containers:
  - name: nginx-pod
    image: nginx
