apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
  name: ssh
  labels:
    run: ssh
  template:
    metadata:
      labels:
        app: nginx

spec:
  containers:
  - name: ssh
    image: erdia22/sshd:0.1  # 이미지 당 단일 Process 실행 권고
    command:
      - "/bin/sh"
      - "-c"
      - "sleep inf"
