apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.9
    heritage: Helm
    release: minio
  name: minio-svc
  namespace: minio
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: minio
  sessionAffinity: None
  type: ClusterIP
