kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: erp01-namespace-full-access
  namespace: erp01
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]