# pipeline 에서 task 전달하는 params, resource 설정 가능

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push-deploy
  namespace: tekton
spec:
  resources:
    - name: git-source
      type: git
    - name: image-repo
      type: image
  tasks:
    - name: build-push
      taskRef:
        name: build-push
      params:
        - name: pathToDockerFile
          value: tomcat-board.dockerfile
        - name: pathToContext
          value: $(resources.inputs.git-source.path)/src
        - name: imageTag
          value: "1.0.5"
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: image-repo
            resource: image-repo

    - name: deploy-using-kubectl
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - build-push
      params:
        - name: path
          value: $(resources.inputs.git-source.path)/deploy/tomcat-board.yml #configure: may change according to your source
        # - name: yamlPathToImage
        #   value: "$(resources.inputs.image-repo.url)" 
        - name: imageTag
          value: "1.0.5"
      resources:
        inputs:
          - name: git-source
            resource: git-source  # 위에서 선언하고 다시 선언하는 이유는?
          - name: image-repo
            resource: image-repo
