apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jerry-git
spec:
  type: git
  params:
  - name: url
    value: https://172.17.16.182/jerry/admin
  - name: revision
    value: master
  - name: sslVerify
    value: 'false'
