apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: imageTag
      type: string
      description: image Tag name
    # - name: yamlPathToImage
    #   type: string
    #   description: |
    #     The path to the image to replace in the yaml manifest (arg to yq)
  resources:
    inputs:
      - name: git-source
        type: git
      - name: image-repo
        type: image
  steps:
    - name: update-yaml
      image: mikefarah/yq
      command: ["yq"]
      args:
        # - "w"
        - "e"
        - '.spec.template.spec.containers.[].image="$(resources.inputs.image-repo.url):$(params.imageTag)"'
        - "-i"
        - "$(params.path)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        # - "/workspace/git-source/$(inputs.params.pathToYamlFile)"
        - "$(params.path)"
