apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push
  namespace: tekton
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      # default: $(resources.inputs.git-source.path)/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      # default: $(resources.inputs.git-source.path)
    - name: imageTag
      type: string
      description: image tag name
      default: latest
  resources:
    inputs:
      - name: git-source
        type: git
    outputs:
      - name: image-repo
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.image-repo.url):$(params.imageTag)
        - --context=$(params.pathToContext)
        - --skip-tls-verify  # https 가 아닌 http 보내는 에러 해결


