apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  loadBalancerIP: 172.17.29.164
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    # nodePort: 30080
  selector:
    app: httpd
    heritage: helm
  type: LoadBalancer