apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ext
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:  # 선택해야 할 POD 선택
    app: nginx  # Deploy Label 과 동일
  externalIPs:
    - 172.17.29.120
