apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: imxc
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus
  type: NodePort

