apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-dev-sBvgn2RJ
  region: ap-northeast-2
managedNodeGroups:
  - name: ng-1-workers
    instanceTypes: ["t3.xlarge","t3a.large"]
    spot: true
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true
