apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: default
spec:
  serviceName: "busybox"
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        diamanti.com/endpoint0: '{"endpointId":"ep1","perfTier":"high"}'  # network 이름 지정
    spec:
      containers:
      - name: busybox
        # image: k8s.gcr.io/busybox-slim:0.8
        image: busybox
        ports:
        - containerPort: 80
          name: web
        command:
        - "/bin/sh"
        - "-c"
        - "sleep inf"

        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 80
        #   failureThreshold: 15
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 1
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "rook-cephfs"
      storageClassName: "high2m"
      resources:
        requests:
          storage: 1Gi   
