apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-hs
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  ports:
  - port: 9092 
    name: client
  clusterIP: None
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
